#pragma once
#include <stdint.h>

typedef struct Point_t {
  float x;
  float y;
} Point;

enum UnitAction {
  UNIT_MOVE = 0x101,
  UNIT_ATTACK = 0x100
};

enum UnitTypeDef {
  IDLE = 0x186A0,
  UNIT_FEMALE_CITIZEN = 0x5AB,
  UNIT_MALE_CITIZEN = 0x432,
  CAPITOL = 0x41D,
  TOWN_CENTER = 0x401,

  UNIT_PREHISTORIC_ROCK_THROWER = 0x3ED,
  UNIT_PREHISTORIC_CLUBMAN = 0x431,
  UNIT_PREHISTORIC_PRIEST = 0x434,
  UNIT_PREHISTORIC_PROPHET = 0x435,
  BUILDING_PREHISTORIC_BARACKS = 0x42F,
  BUILDING_PREHISTORIC_HOUSE = 0x42D,
  BUILDING_PREHISTORIC_TOWER = 0x3EF,
  BUILDING_PREHISTORIC_CHURCH = 0x433,

  UNIT_STONE_PRIEST = 0x434,
  UNIT_STONE_PROPHET = 0x435,
  UNIT_STONE_ROCK_THROWER = 0x3ED,
  UNIT_STONE_CLUBMAN = 0x431,
  UNIT_STONE_SPEARMAN = 0x7E8,
  UNIT_STONE_SAMPSON = 0x7D4,
  UNIT_STONE_SLINGER = 0x7D9,
  UNIT_STONE_FISING_BOAT = 0x7D0,
  UNIT_STONE_TRANSPORT = 0x7D2,
  UNIT_STONE_FRIGATE = 0x7D1,
  BUILDING_STONE_BARACKS = 0x42F,
  BUILDING_STONE_ARCHERY = 0x806,
  BUILDING_STONE_CHURCH = 0x433,
  BUILDING_STONE_PORT = 0x7E7,

  UNIT_COPPER_PRIEST = 0x434,
  UNIT_COPPER_PROPHET = 0x435,
  UNIT_COPPER_MACEMAN = 0xBC3,
  UNIT_COPPER_SPEARMAN = 0x7E8,
  UNIT_COPPER_SAMPSON = 0x7D4,
  UNIT_COPPER_BOWMAN = 0xBCA,
  UNIT_COPPER_HORSEMAN = 0xBCC,
  UNIT_COPPER_FISING_BOAT = 0x7D0,
  UNIT_COPPER_TRANSPORT = 0xBDF,
  UNIT_COPPER_BATTLESHIP = 0xBBF,
  UNIT_COPPER_FRIGATE = 0xBE1,
  UNIT_COPPER_GALLEY = 0xBE0,
  BUILDING_COPPER_BARACKS = 0x42F,
  BUILDING_COPPER_ARCHERY = 0x806,
  BUILDING_COPPER_CHURCH = 0x433,
  BUILDING_COPPER_PORT = 0x7E7,
  BUILDING_COPPER_STABLE = 0xBC6,
  BUILDING_COPPER_HOUSE = 0x42D,
  BUILDING_COPPER_TOWER = 0xBEE,
  BUILDING_COPPER_WALL = 0xBED,
  BUILDING_COPPER_UNIVERSITY = 0xBF0,
  BUILDING_COPPER_HOSPITAL = 0xC1D,
  BUILDING_COPPER_GRANARY = 0xC0A,
  BUILDING_COPPER_GRANARY_FIELD = 0xBC8,
  BUILDING_COPPER_FORTRESS = 0xC00,

  UNIT_BRONZE_SHORT_SWORD = 0xFB7,
  UNIT_BRONZE_PHALANX = 0xFBD,
  UNIT_BRONZE_JAVELYN = 0xFA2,
  UNIT_BRONZE_BOWMAN = 0xBCA,
  UNIT_BRONZE_CHARIOT = 0xFD4,
  UNIT_BRONZE_ELEPHANT_ARCHER = 0xFB8, // Something wrong here
  UNIT_BRONZE_FISING_BOAT = 0xFA5,
  UNIT_BRONZE_TRANSPORT = 0x100C,
  UNIT_BRONZE_BATTLESHIP = 0xFBB,
  UNIT_BRONZE_FRIGATE = 0xFC3,
  UNIT_BRONZE_GALLEY = 0xFD8,
  UNIT_BRONZE_HORSEMAN = 0xBCC,
  UNIT_BRONZE_CAVALRY = 0xFC4,
  UNIT_BRONZE_WAR_ELEPHANT = 0xFC8,
  BUILDING_BRONZE_BARACKS = 0x42F,
  BUILDING_BRONZE_ARCHERY = 0x806,
  BUILDING_BRONZE_STABLE = 0xBC6,
  BUILDING_BRONZE_SIEGE_FACTORY = 0xFC1,
  BUILDING_BRONZE_HOSPITAL = 0xC1D,
  BUILDING_BRONZE_UNIVERSITY = 0xBF0,
  BUILDING_BRONZE_TOWN_CENTER = 0x401,
  BUILDING_BRONZE_HOUSE = 0x42D,
  BUILDING_BRONZE_PORT = 0x7E7,
  BUILDING_BRONZE_WALL = 0xFDE,
  BUILDING_BRONZE_TOWER = 0x3EF,
  BUILDING_BRONZE_FORTRESS = 0xC00,

  // From here, there would be only water or air units. (or under water).
  UNIT_DARK_TRANSPORT = 0x100C,
  UNIT_DARK_FISING_BOAT = 0xFA5,
  UNIT_DARK_FISING_BATTLESHIP = 0x1390,
  UNIT_DARK_FISING_FRIGATE = 0x1397,
  UNIT_DARK_GALLEY = 0x13AD,

  UNIT_MIDDLE_FISING_BOAT = 0xFA5,
  UNIT_MIDDLE_TRANSPORT = 0x100C,
  UNIT_MIDDLE_BATTLESHIP = 0x1771,
  UNIT_MIDDLE_FRIGATE = 0x1796,
  UNIT_MIDDLE_GALLEY = 0x17AE,

  UNIT_RENA_TRANSPORT = 0x100C,
  UNIT_RENA_FISING_BOAT = 0xFA5,
  UNIT_RENA_BATTLESHIP = 0x1B66,
  UNIT_RENA_FRIGATE = 0x1B5C,
  UNIT_RENA_GALLEY = 0x1B96,

  UNIT_IMPERIAL_TRANSPORT = 0x1F54,
  UNIT_IMPERIAL_FISING_BOAT = 0x1F9A,
  UNIT_IMPERIAL_BATTLESHIP = 0x1F50,
  UNIT_IMPERIAL_FRIGATE = 0x1F47,
  UNIT_IMPERIAL_GALLEY = 0x1F7E,

  UNIT_INDUSTRIAL_TRANSPORT = 0x1F54,
  UNIT_INDUSTRIAL_FISING_BOAT = 0x1F9A,
  UNIT_INDUSTRIAL_BATTLESHIP = 0x2339,
  UNIT_INDUSTRIAL_FRIGATE = 0x233C,
  UNIT_INDUSTRIAL_GALLEY = 0x2367,
  UNIT_INDUSTRIAL_CRUISER = 0x1F98,
  UNIT_INDUSTRIAL_BALOON = 0x2333,

  // ww1
  UNIT_WW1_TRANSPORT = 0x272C,
  UNIT_WW1_FISING_BOAT = 0x2B52,
  UNIT_WW1_BATTLESHIP = 0x2B20,
  UNIT_WW1_FRIGATE = 0x2743,
  UNIT_WW1_CRUISER = 0x271C,
  UNIT_WW1_SUBMARIN = 0x2741,

  // aircrafts
  UNIT_WW1_LIGHTER_BOMBER = 0x2722,
  UNIT_WW1_SOPWITH = 0x2715,
  UNIT_WW1_GOTHA_BOMBER = 0x2729,
  UNIT_WW1_BALOON = 0x273A,

  // ww2
  UNIT_WW2_TRANSPORT = 0x272C,
  UNIT_WW2_FISING_BOAT = 0x1F9A,
  UNIT_WW2_BATTLESHIP = 0x272D,
  UNIT_WW2_FRIGATE = 0x2B21,
  UNIT_WW2_CRUISER = 0x271C,
  UNIT_WW2_CARRIER = 0x2B26,
  UNIT_WW2_SUBMARIN = 0x2741,

  // aircrafts
  UNIT_WW2_M246_LIGHTER_BOMBER = 0x2B00,
  UNIT_WW2_SOPWITH = 0x2AF8,
  UNIT_WW2_M1_BOMBER = 0x2AF9,
  UNIT_WW2_B29_BOMBER = 0x2B3F,
  UNIT_WW2_ANTI_TANK = 0x2B4D,
  UNIT_WW2_BALOON = 0x273A,
  UNIT_WW2_CARRIER_PLANE = 0x2B1B,

  // wwm
  UNIT_WWM_TRANSPORT = 0x272C,
  UNIT_WWM_FISING_BOAT = 0x2B52,
  UNIT_WWM_BATTLESHIP = 0x2B20,
  UNIT_WWM_FRIGATE = 0x2743,
  UNIT_WWM_CRUISER = 0x271C,
  UNIT_WWM_BALOON = 0x273A,
  UNIT_WWM_CARRIER = 0x2B26,
  UNIT_WWM_SUB_TRIDENT = 0x2EF1,
  UNIT_WWM_SUBMARIN = 0x2EE9,

  // aircrafts
  UNIT_WWM_M246_LIGHTER_BOMBER = 0x2EFC,
  UNIT_WWM_LIGHTER = 0x2EE1,
  UNIT_WWM_B_2_BOMBER = 0x2F4F,
  UNIT_WWM_B52_BOMBER = 0x2F1D,
  UNIT_WWM_ANTI_TANK = 0x2EE0,
  UNIT_WWM_SEE_KING = 0x2EF0,
  UNIT_WWM_HELICOPTER = 0x2EE4,
  UNIT_WWM_HELICOPTER_ANTI_TANK = 0x2EE3,
  UNIT_WWM_HELICOPTER_GUNSHIP = 0x2EE2,
  UNIT_WWM_CARRIER_PLANE = 0x2EEF,

  // digital
  UNIT_DIGITAL_TRANSPORT = 0x3327,
  UNIT_DIGITAL_FISING_BOAT = 0x332A,
  UNIT_DIGITAL_BATTLESHIP = 0x32EF,
  UNIT_DIGITAL_FRIGATE = 0x32F0,
  UNIT_DIGITAL_CRUISER = 0x32EA,
  UNIT_DIGITAL_PORT_NAVAL = 0x32FE,
  UNIT_DIGITAL_SUBMARIN = 0x2EE9,
  UNIT_DIGITAL_SUB_TRIDENT = 0x2EF1,

  // aircrafts
  UNIT_DIGITAL_TALON_LIGHTER_BOMBER = 0x3324,
  UNIT_DIGITAL_JACKAL = 0x32D2,
  UNIT_DIGITAL_WIVERN = 0x3316,
  UNIT_DIGITAL_TITAN_BOMBER = 0x331D,
  UNIT_DIGITAL_ANTI_TANK = 0x2EE0,
  UNIT_DIGITAL_SEE_KING = 0x2EF0,
  UNIT_DIGITAL_PEGASUS = 0x3393,
  UNIT_DIGITAL_SPECTRE = 0x32C8,
  UNIT_DIGITAL_REAPER = 0x3314,
  UNIT_DIGITAL_ARES = 0x3392,
  UNIT_DIGITAL_APOLLO = 0x332C,
  UNIT_DIGITAL_NAVAL_BOMBER = 0x32D7,

  // Nano age
  UNIT_NANO_TRANSPORT = 0x3327,
  UNIT_NANO_FISING_BOAT = 0x332A,
  UNIT_NANO_BATTLESHIP = 0x32EF,
  UNIT_NANO_FRIGATE = 0x32F0,
  UNIT_NANO_CRUISER = 0x32EA,
  UNIT_NANO_PORT_NAVAL = 0x32FE,

  // aircrafts
  UNIT_NANO_PHOENIX = 0x36C6,
  UNIT_NANO_NEBULA = 0x36D2,
  UNIT_NANO_WIVERN = 0x3316,
  UNIT_NANO_TITAN_BOMBER = 0x331D,
  UNIT_NANO_ANTI_TANK = 0x2EE0,
  UNIT_NANO_SEE_KING_2 = 0x36BB,
  UNIT_NANO_PEGASUS = 0x3393,
  UNIT_NANO_SPECTRE = 0x32C8,
  UNIT_NANO_REAPER = 0x3314,
  UNIT_NANO_ARES_2 = 0x3783,
  UNIT_NANO_APOLLO = 0x332C,
  UNIT_NANO_NAVAL_BOMBER = 0x32D7,

  UNIT_SPACE_CAPITAL_SHIP = 0x3A99,
  UNIT_SPACE_SPACE_CARRIER = 0x3A9D,
  UNIT_SPACE_CAPITAL_TRANSPORT = 0x3A9E,
  UNIT_SPACE_CAPITAL_CORVETTE = 0x3A9F,
  UNIT_SPACE_PANE = 0x3AA2,
};

uint8_t eeTypes_IsWorker(UnitTypeDef type);
uint8_t eeTypes_CanProduceWorkers(UnitTypeDef type);
void eeTypes_OnInit();
uint8_t eeTypes_IsTransport(UnitTypeDef type);
uint8_t eeTypes_IsAir(UnitTypeDef type);
uint8_t eeTypes_IsWater(UnitTypeDef type);
uint8_t eeTypes_IsGround(UnitTypeDef type);
uint8_t eeTypes_IsFishBoat(UnitTypeDef type);